#!/bin/sh

# STAGED_JS_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".js\{0,1\}$")
# ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"
# JS_PASS=true

# if [ "$STAGED_JS_FILES" != "" ]; then
#   printf "\nRunning lint:js:\n"

#   # Check for eslint
#   if [[ ! -x "$ESLINT" ]]; then
#     printf "\t\033[41mPlease install ESlint\033[0m (npm i --save-dev eslint)"
#     exit 1
#   fi
#   for FILE in $STAGED_JS_FILES
#   do
#     "$ESLINT" "$FILE"

#     if [[ "$?" == 0 ]]; then
#       printf "\t\033[32mlint:js Passed: $FILE\033[0m"
#     else
#       printf "\t\033[41mlint:js Failed: $FILE\033[0m"
#       JS_PASS=false
#     fi
#   done
# fi
# printf "\nlint:js completed!\n"

# STAGED_HBS_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".hbs\{0,1\}$")
# HBSLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/ember-template-lint"
# HBS_PASS=true
# if [ "$STAGED_HBS_FILES" != "" ]; then
#   printf "\nRunning lint:hbs:\n"

#   # Check for eslint
#   if [[ ! -x "$HBSLINT" ]]; then
#     printf "\t\033[41mPlease install ember-template-lint\033[0m (npm i --save-dev ember-template-lint)"
#     exit 1
#   fi
#   for FILE in $STAGED_HBS_FILES
#   do
#     "$HBSLINT" "$FILE"

#     if [[ "$?" == 0 ]]; then
#       printf "\t\033[32mlint:hbs Passed: $FILE\033[0m"
#     else
#       printf "\t\033[41mlint:hbs Failed: $FILE\033[0m"
#       HBS_PASS=false
#     fi
#   done
# fi
# printf "\nlint:hbs completed!\n"

# if ! $JS_PASS; then
#   printf "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass lint:js but do not. Please fix the lint:js errors and try again.\n"
#   exit 1
# elif ! $HBS_PASS; then
#   printf "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass lint:hbs but do not. Please fix the lint:hbs errors and try again.\n"
#   exit 1
# else
#   printf "\033[42mCOMMIT SUCCEEDED\033[0m\n"
# fi

npx lint-staged

exit $?